### PR TITLE
ChatImprovements_v2

### PR DESCRIPTION
**Pull request by Sossenbinder**
- Made it possible for the chat to slide out of the view
- Some formatting

### CODE REVIEW

**Comment by Sossenbinder** [comment]
One question regarding the svg icons: Where do you get them from? I'd probably need a chat button with the vertical line through to make it clear that the chat is turned off, on top of the background color.

**Comment by Sossenbinder** [comment]
Anyways, with this change there is now a good possibility to work with more space in mobile mode - Next thing to tackle for the buttons I'd say.

**Comment by fayrtv** [comment]
> One question regarding the svg icons: Where do you get them from? I'd probably need a chat button with the vertical line through to make it clear that the chat is turned off, on top of the background color.

Here you can find two SVG libraries I'm using:
- https://ionic.io/ionicons
- https://iconsvg.xyz/

**Comment by Sossenbinder** [comment]
> > One question regarding the svg icons: Where do you get them from? I'd probably need a chat button with the vertical line through to make it clear that the chat is turned off, on top of the background color.
> 
> Here you can find two SVG libraries I'm using:
> 
> * https://ionic.io/ionicons
> * https://iconsvg.xyz/

Gotcha, thanks. Sadly no chat icon with a diagonal line to mark it as "off", but I think the background is good enough 👍

**Pull request merged**
